In [8]:
#Just playing with arrays
import numpy

In [23]:
A = numpy.arange(8).reshape(2, 2, 2)
B = numpy.arange(4).reshape(2, 2)
A+B

array([[[ 0,  2],
        [ 4,  6]],

       [[ 4,  6],
        [ 8, 10]]])

#Performing pythagorean theorem where the parameters are a and b, all three lengths are outputted

In [5]:
import math
def pythagorean(a, b):

    if type(a) != float or type(b) != float:
        return(None)
    
    c= math.sqrt(a**2 + b**2)
    
    return(a, b, c)
pythagorean_triple(3., 4.)

NameError: name 'pythagorean_triple' is not defined

#User gets to print a string for their desired number of repetitions

In [6]:
def repeat():

    repeat = input("Input loop string: ")

    number_string = input("Input number of repetitions: ")

    if not number_string.isnumeric():
        return(None)

    number = int(number_string)

    for i in range(number):
        print(repeat)

#Parameters are types (func, float, float, int)
#The first float is interval for the x coordinate
#The second float is the interval for the y coordinate
#The integer is the shape and the number of arrays

#The first array is evaluates the multiplication of the x and y coordinates at each point
#The second array returned is with x-coordinates evenly spaced
#The third array returned is with y-coordinates evenly spaced

In [9]:

def func(x, y):
    return(x*y)

def project_to_grid(func, xlim, ylim, N):

    if type(xlim) != float or type(ylim) != float or type(N) != int:
        return(None)
    
    if xlim <= 0. or ylim <= 0. or N < 1: 
            return (None)
   
    xvec = numpy.linspace(0, xlim, N)
    yvec = numpy.linspace(0, ylim, N)
    print(xvec)
    x = numpy.empty((N, N))
    y = numpy.empty((N, N))
    
    for i in range(N):
        x[i,:] = xvec
        y[:, i] = yvec
    
    f = func(x, y)
    return (f, x, y)
project_to_grid(func, 10., 10., 3)

[ 0.  5. 10.]


(array([[  0.,   0.,   0.],
        [  0.,  25.,  50.],
        [  0.,  50., 100.]]),
 array([[ 0.,  5., 10.],
        [ 0.,  5., 10.],
        [ 0.,  5., 10.]]),
 array([[ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [10., 10., 10.]]))